services:
  web:
    image: distucker/spring-petclinic:be09260e42b4907cdc642295eea0d3c4543c16bc
    environment:
      SPRING_PROFILES_ACTIVE: postgres
      POSTGRES_URL: jdbc:postgresql://postgres:5432/petclinic 
      POSTGRES_USER_FILE: /run/secrets/db_username  
      POSTGRES_PASS_FILE: /run/secrets/db_password  
    secrets:
      - db_username
      - db_password
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: always 
    deploy:
      replicas: 3 
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
    
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: petclinic
      POSTGRES_USER_FILE: /run/secrets/db_username  
      POSTGRES_PASS_FILE: /run/secrets/db_password  
    secrets:
      - db_username
      - db_password
    ports:
      - "5432:5432"
    restart: always # Automatically restart if it fails
    healthcheck: # Check if PostgreSQL is ready
      test: ["CMD-SHELL", "pg_isready -U petclinic"]
      interval: 30s
      timeout: 15s
      retries: 10
    deploy:
      replicas: 2 # Specify 1 replica for PostgreSQL
      restart_policy:
        condition: any
    volumes:
      - db_data:/var/lib/postgresql/data # Persistent storage
volumes:
  db_data:
secrets:
  db_username:
    external: true
  db_password:
    external: true